<?php

/**
 * @file
 * Contains ngf_geo_import.module.
 */

/**
 * Implements hook_migration_plugins_alter().
 */
function ngf_geo_import_migration_plugins_alter(&$definitions) {
  $definitions['ngf_countries']['source']['path'] = drupal_get_path('module', 'ngf_geo_import') . $definitions['ngf_countries']['source']['path'];
  $definitions['ngf_regions']['source']['path'] = drupal_get_path('module', 'ngf_geo_import') . $definitions['ngf_regions']['source']['path'];
  $definitions['ngf_cities']['source']['path'] = drupal_get_path('module', 'ngf_geo_import') . $definitions['ngf_cities']['source']['path'];
}
